on:
  push:
    branches:
    - main

jobs:
  build:
    name: run static page generator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: make generate

    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: go-anx-io.lf-net.org
        force_orphan: true
